{% set name = "silx" %}
{% set version = "0.12.0" %}
{% set sha256 = "2346ee44eb65ffa23c82d86f401282ea0fde0b813f897f178d901ec09889b9dc" %}

package:
  name: silx-base
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

outputs:
  - name: silx-base
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    build:
      entry_points:
        - silx = silx.__main__:main

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - cython
        - pip
        - python
        - setuptools
        - numpy >=1.12
      run:
        - python
        - setuptools
        - {{ pin_compatible('numpy') }}
        - fabio >=0.9
        - h5py
        - six
        - enum34  # [py2k]
        - futures  # [py2k]

    test:
      imports:
        - silx
        - silx.test

  - name: silx
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('silx-base', exact=True) }}
        - mako
        - ipython
        - qtconsole
        - matplotlib
        - python-dateutil
        - pyqt
        - scipy
        - pillow
        # optional dep causing lots of problems
        #- pyopengl

about:
  home: https://github.com/silx-kit/silx
  license: MIT
  license_family: MIT
  license_file: copyright
  summary: 'The silx project aims at providing a collection of Python packages
  to support the development of data assessment, reduction and analysis
  applications at synchrotron radiation facilities.'

  description: |
    The silx project aims at providing a collection of Python packages to
    support the development of data assessment, reduction and analysis
    applications at synchrotron radiation facilities. It aims at providing
    reading/writing different file formats, data reduction routines and a set
    of Qt widgets to browse and visualize data.
  doc_url: http://www.silx.org/doc/silx/latest/
  dev_url: https://github.com/silx-kit/silx

extra:
  recipe-maintainers:
    - CJ-Wright
    - tschoonj
    - vallsv
    - t20100
