travis:
  secure:
    BINSTAR_TOKEN: s7XrokhNlfUdsbzfYfpLzNcKQwUZDYvJh8qRq43o0M8TJsQGxnmFalKjut9V2DkuiPneFUD320zXzS9J5rPlhCecIMA3QMAUUajKTx726yia4zWYlgK8BCE2qJWQUG0U1QDbZh6tRl9hSOkqW9yAUtPHR5UX/seVDVcU3xFDPpzLNIxXSSlbbrPHvbsrCx70M+G6eMRScLaMGJ0HOEEzhksbzXWrHdOcqGTzJ/D5Hqx01bW40eFqJax0y+UCkyVca6uA69rjFv0ICEa5z33gffFoQxlB2B+o25sxSwtWKriKKSEKIwrR0MJu+6IDqe90kKcdBCytI2mHKcQtuztTNPEVSXs6aVerwiWQTwydVQN81IZGO6tOMHBWbasNLXZjcseoECGFsy2q3amaYjXd4ctL1TxAxK4X5AcV2zf7EAjFT49UtyEqAdO6s2WWSc9JrwY/c8l0BXxr6MJbX8sgZP0CrdXjN4BLcNLrxBcde6u3KgcqjI6JfhDNDOdlLw76Sfpqbf/mqBmTBpszxWti0M/35jdqF0N/7G0RWPN3zUUSSXO0n6OWI2snN95t6YpAfqzUxeQu42MT9F9FFxEDDOQPHf0xzOYSY81FP2ynz3SQKlt1rGXAcxgXya/pirq/ms6EtwaGJe4Phagvfv6a7mMVYwjE6vz1U+WJj8gj1d0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
